name: cybersecurity
recipe: pantheon
config:
  webroot: web
  drush: 9
  php: '7.2'
  framework: drupal8
  site: cybersecurity-yale-edu
  id: 3878688f-3b52-4746-804c-3e2eb786824b
tooling:
  drush:
    service: appserver
    cmd: "drush --root=/app/web --uri=https://cybersecurity.lndo.site"
services:
  # Add an indexing backend
  # See: https://docs.devwithlando.io/services/solr.html
  index:
    type: solr:3.6
    core: collection1
    # Look in `lando info` for the port here. Avoids collisions.
    portforward: true
    config:
      dir: web/modules/contrib/search_api_solr/solr-conf/4.x
