<?php

/**
 * @file
 * Contains yi_core.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function yi_core_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the yi_core module.
    case 'help.page.yi_core':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Yale Infosec Core styles') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_page_attachments().
 */
function yi_core_page_attachments(array &$attachments) {
  $is_admin = \Drupal::service('router.admin_context')->isAdminRoute();
  if ($is_admin) {
    $attachments['#attached']['library'][] = 'yi_core/admin-css';
    return;
  }
}
