<?php

/**
 * @file
 * Contains yi_mss_calculator.module.
 */

use Drupal\Core\Url;
use Drupal\node\Entity\Node;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\yi_mss_calculator\Controller\MSSCalculatorController;

/**
 * Implements hook_help().
 */
function yi_mss_calculator_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the yi_mss_calculator module.
    case 'help.page.yi_mss_calculator':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Minimum Security Standard Calculator') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function yi_mss_calculator_theme() {
  return [
    'yi_mss_calculator_overview' => [
      'variables' => [
        'filters' => [],
        'results' => [],
      ],
    ],
    'yi_mss_calculator_primary' => [
      'variables' => [
        'results' => [],
      ],
    ],
    'yi_mss_calculator_listing_page' => [
      'variables' => [
        'standards' => [],
        'header_text' => NULL,
      ],
    ],
    'yi_mss_calculator_results_download' => [
      'variables' => [
        'results' => [],
        'filters' => [],
      ],
    ],
    'yi_mss_calculator_specifications_grid' => [
      'variables' => [
        'title' => NULL,
        'uri' => NULL,
        'specifications' => [],
      ],
    ],
  ];
}

/**
 * Implements template_preprocess_node().
 *
 * Injects title and URI for parent standard, if any.
 */
function yi_mss_calculator_preprocess_node(&$variables) {
  if ($variables['view_mode'] === 'full' && $variables['node']->bundle() == 'standard') {
    $parent_nid = MSSCalculatorController::getParentNid($variables['node']->id());
    if ($parent_nid) {
      $parent = Node::load($parent_nid);
      $uri = Url::fromRoute('entity.node.canonical', ['node' => $parent_nid], ['absolute' => TRUE])->toString();
      $variables['parent_standard'] = $uri;
      $variables['parent_standard_title'] = $parent->getTitle();
    }
  }
}
